language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind
  - g++ -v

script: make && make test

after_success: make checkmemoryleak

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
